-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 23:33:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_6` DEFAULT CHARACTER SET utf8 ;
USE `db_6` ;

-- -----------------------------------------------------
-- Table `db_6`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_6`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(255) NULL,
  `brand` VARCHAR(255) NULL,
  `client_id` INT NULL,
  `modification_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_6`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_6`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NULL,
  `auto_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_danish_ci;


-- -----------------------------------------------------
-- Table `db_6`.`modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_6`.`modification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NULL,
  `power` INT NULL,
  `drive_unit` INT NULL,
  `auto_id` INT NOT NULL,
  `client_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modification_auto_idx` (`auto_id` ASC) VISIBLE,
  INDEX `fk_modification_client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_modification_auto`
    FOREIGN KEY (`auto_id`)
    REFERENCES `db_6`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modification_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `db_6`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_6`.`specification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_6`.`specification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `run` INT NULL,
  `cost` INT NULL,
  `sale_date` DATE NULL,
  `modification_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_specification_modification1_idx` (`modification_id` ASC) VISIBLE,
  CONSTRAINT `fk_specification_modification1`
    FOREIGN KEY (`modification_id`)
    REFERENCES `db_6`.`modification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
